[
	"fileversion","22.0.368",
	"hasindex",false,
	"pointcount",8,
	"vertexcount",24,
	"primitivecount",6,
	"info",{
		"artist":"arusev",
		"software":"Houdini 22.0.368",
		"date":"2026-09-19 17:18:16",
		"hostname":"nvbeast-linux",
		"bounds":[-1,1,-1,1,-1,1],
		"primcount_summary":"          6 Polygons\n",
		"attribute_summary":"     2 vertex attributes:\tuv, N\n     8 point attributes:\tCd, pscale, P, my_int_array, ptname, my_dict_array_attr, my_str_array, my_float_array\n     2 primitive attributes:\tshop_materialpath, primname\n     1 global attributes:\tmy_dict_attr\n",
		"group_summary":"     1 point groups:\t\tgroup_B\n     1 primitive groups:\tgroup_A\n"
	},
	"topology",[
		"pointref",[
			"indices",[1,5,4,0,2,6,5,1,3,7,6,2,0,4,7,3,2,1,0,3,5,6,7,4]
		]
	],
	"attributes",[
		"vertexattributes",[
			[
				[
					"scope","public",
					"type","numeric",
					"name","N",
					"options",{
						"type":{
							"type":"string",
							"value":"normal"
						}
					}
				],
				[
					"size",3,
					"storage","fpreal32",
					"defaults",[
						"size",1,
						"storage","fpreal64",
						"values",[0]
					],
					"values",[
						"size",3,
						"storage","fpreal32",
						"tuples",[[0,0,-1],[0,0,-1],[0,0,-1],[0,0,-1],[1,0,0],[1,0,0],[1,0,0],[1,0,0],[0,0,1],[0,0,1],[0,0,1],[0,0,1],[-1,0,0],[-1,0,0],[-1,0,0],[-1,0,0],[0,-1,0],[0,-1,0],[0,-1,0],[0,-1,0],[0,1,0],[0,1,0],[0,1,0],[0,
								1,0]
						]
					]
				]
			],
			[
				[
					"scope","public",
					"type","numeric",
					"name","uv",
					"options",{
						"type":{
							"type":"string",
							"value":"texturecoord"
						}
					}
				],
				[
					"size",3,
					"storage","fpreal32",
					"defaults",[
						"size",1,
						"storage","fpreal64",
						"values",[0]
					],
					"values",[
						"size",3,
						"storage","fpreal32",
						"tuples",[[1,0,0],[1,0,1],[0,0,1],[0,0,0],[1,1,0],[1,1,1],[1,0,1],[1,0,0],[0,1,0],[0,1,1],[1,1,1],[1,1,0],[0,0,0],[0,0,1],[0,1,1],[0,1,0],[1,1,0],[1,0,0],[0,0,0],[0,1,0],[1,0,1],[1,1,1],[0,1,1],[0,0,1]
						]
					]
				]
			]
		],
		"pointattributes",[
			[
				[
					"scope","public",
					"type","numeric",
					"name","P",
					"options",{
						"type":{
							"type":"string",
							"value":"point"
						}
					}
				],
				[
					"size",3,
					"storage","fpreal32",
					"defaults",[
						"size",1,
						"storage","fpreal64",
						"values",[0]
					],
					"values",[
						"size",3,
						"storage","fpreal32",
						"tuples",[[-1,-1,-1],[1,-1,-1],[1,-1,1],[-1,-1,1],[-1,1,-1],[1,1,-1],[1,1,1],[-1,1,1]
						]
					]
				]
			],
			[
				[
					"scope","public",
					"type","numeric",
					"name","Cd",
					"options",{
						"type":{
							"type":"string",
							"value":"color"
						}
					}
				],
				[
					"size",3,
					"storage","fpreal32",
					"defaults",[
						"size",1,
						"storage","fpreal64",
						"values",[1]
					],
					"values",[
						"size",3,
						"storage","fpreal32",
						"tuples",[[0,0,0],[1,0,0],[1,0,1],[0,0,1],[0,1,0],[1,1,0],[1,1,1],[0,1,1]
						]
					]
				]
			],
			[
				[
					"scope","public",
					"type","dictarray",
					"name","my_dict_array_attr",
					"options",{
					}
				],
				[
					"storage","int32",
					"size",1,
					"dicts",[
						{
							"sample":{
								"type":"int",
								"value":0
							}
						},
						{
							"sample":{
								"type":"int",
								"value":1
							}
						},
						{
							"sample":{
								"type":"int",
								"value":2
							}
						},
						{
							"sample":{
								"type":"int",
								"value":3
							}
						},
						{
							"sample":{
								"type":"int",
								"value":4
							}
						},
						{
							"sample":{
								"type":"int",
								"value":5
							}
						},
						{
							"sample":{
								"type":"int",
								"value":6
							}
						}
					],
					"indices",[[],[0],[0,1],[0,1,2],[0,1,2,3],[0,1,2,3,4],[0,1,2,3,4,5],[0,1,2,3,4,5,6]
					]
				]
			],
			[
				[
					"scope","public",
					"type","arraydata",
					"name","my_float_array",
					"options",{
					}
				],
				[
					"storage","fpreal32",
					"size",1,
					"values",[[0,0,0],[1,2,3],[2,4,6],[3,6,9],[4,8,12],[5,10,15],[6,12,18],[7,14,21]
					]
				]
			],
			[
				[
					"scope","public",
					"type","arraydata",
					"name","my_int_array",
					"options",{
					}
				],
				[
					"storage","int32",
					"size",1,
					"values",[[0,0,0,-1],[1,2,3],[2,4,6],[3,6,9],[4,8,12],[5,10,15],[6,12,18],[7,14,21,-1]
					]
				]
			],
			[
				[
					"scope","public",
					"type","stringarray",
					"name","my_str_array",
					"options",{
					}
				],
				[
					"storage","int32",
					"size",1,
					"strings",["pt_0_0","pt_0_1","pt_0_2","start","pt_1_0","pt_1_1","pt_1_2","pt_2_0","pt_2_1","pt_2_2","pt_3_0","pt_3_1","pt_3_2","pt_4_0","pt_4_1","pt_4_2","pt_5_0","pt_5_1","pt_5_2","pt_6_0","pt_6_1","pt_6_2","pt_7_0",
						"pt_7_1","pt_7_2","end"
					],
					"indices",[[0,1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24,25]
					]
				]
			],
			[
				[
					"scope","public",
					"type","numeric",
					"name","pscale",
					"options",{
					}
				],
				[
					"size",1,
					"storage","fpreal32",
					"defaults",[
						"size",1,
						"storage","fpreal64",
						"values",[0]
					],
					"values",[
						"size",1,
						"storage","fpreal32",
						"arrays",[[0.417231798,0.879700184,0.884325743,0.0383453369,0.573059916,0.312632084,0.523001909,0.802184343]
						]
					]
				]
			],
			[
				[
					"scope","public",
					"type","string",
					"name","ptname",
					"options",{
					}
				],
				[
					"size",1,
					"storage","int32",
					"strings",["point_0","point_1","point_2","point_3","point_4","point_5","point_6","point_7"
					],
					"indices",[
						"size",1,
						"storage","int32",
						"arrays",[[0,1,2,3,4,5,6,7]
						]
					]
				]
			]
		],
		"primitiveattributes",[
			[
				[
					"scope","public",
					"type","string",
					"name","primname",
					"options",{
					}
				],
				[
					"size",1,
					"storage","int32",
					"strings",["prim_0","prim_1","prim_2","prim_3","prim_4","prim_5"
					],
					"indices",[
						"size",1,
						"storage","int32",
						"arrays",[[0,1,2,3,4,5]
						]
					]
				]
			],
			[
				[
					"scope","public",
					"type","string",
					"name","shop_materialpath",
					"options",{
					}
				],
				[
					"size",1,
					"storage","int32",
					"strings",["/obj/hapi_geo1/geo/shopnet1/red_material","/obj/hapi_geo1/geo/shopnet1/green_material"
					],
					"indices",[
						"size",1,
						"storage","int32",
						"arrays",[[0,0,0,0,1,1]
						]
					]
				]
			]
		],
		"globalattributes",[
			[
				[
					"scope","public",
					"type","dict",
					"name","my_dict_attr",
					"options",{
					}
				],
				[
					"size",1,
					"storage","int32",
					"dicts",[
						{
							"dict":{
								"type":"dict",
								"value":{
									"foo":{
										"type":"int",
										"value":3
									}
								}
							},
							"int_key":{
								"type":"int",
								"value":1
							},
							"list":{
								"type":"intarray",
								"value":[1,2,3]
							},
							"str_key":{
								"type":"string",
								"value":"text"
							}
						}
					],
					"indices",[
						"size",1,
						"storage","int32",
						"arrays",[[0]
						]
					]
				]
			]
		]
	],
	"primitives",[
		[
			[
				"type","Polygon_run"
			],
			[
				"startvertex",0,
				"nprimitives",6,
				"nvertices_rle",[4,6]
			]
		]
	],
	"pointgroups",[
		[
			[
				"name","group_B"
			],
			[
				"selection",[
					"unordered",[
						"i8",[1,1,1,1,1,1,1,1]
					]
				]
			]
		]
	],
	"primitivegroups",[
		[
			[
				"name","group_A"
			],
			[
				"selection",[
					"unordered",[
						"i8",[1,1,1,1,1,1]
					]
				]
			]
		]
	]
]
