[package]
name = "hapi-bindgen"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heck = "0.5.0"
bindgen = "0.71.1"
once_cell = "1.18.0"
argh = "0.1.10"
anyhow = "1.0.71"
